---
global_exemptions: # The roles and/or users below will be ignored in all tests. Regular expressions are supported
- "^arn:aws:iam::(\\d{12}):user/(.*)(ADMIN|admin)(.*)$"
- "^arn:aws:iam::(\\d{12}):role/(.*)(ADMIN|admin)(.*)$"
- "^arn:aws:iam::(\\d{12}):role/AWSCloudFormationStackSetExecutionRole$"
- "^arn:aws:iam::(\\d{12}):role/CloudCustodianRole$"
tests:
- actions:
  - "*:*"
  - iam:*
  - iam:Create*
  - iam:Pass*
  - redshift:*
  - redshift:GetClusterCredentials
  - redshift:JoinGroup
  - rds:*
  - rds-db:connect
  - sts:AssumeRole
  - sts:AssumeRoleWithSAML
  - s3:*
  expected_result: fail
  resources:
  - "*"
  exemptions: []
- actions:
  - sts:AssumeRole
  expected_result: fail
  resources:
  - "arn:aws:iam::{account_id}:role/ASSUME_SYSTEMADMIN_ROLE"
  exemptions: []
- actions:
  - rds:Create*
  - rds:Delete*
  - rds:Modify*
  expected_result: fail
  resources:
  - "*"
  excemptions:
  - "^arn:aws:iam::(.*)(PLATFORM_ENGINEER_ROLE)(.*)$"
- actions:
  - s3:GetObject
  - s3:PutObject
  - s3:CreateBucket
  expected_result: fail
  resources:
  - "*"
  excemptions:
  - "^arn:aws:iam::(.*)(PLATFORM_ENGINEER_ROLE)(.*)$"
